"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


@router.get("/admin/analytics")
async def admin_analytics(request: Request, days: int = Query(28, ge=7, le=365)):
    """Return aggregated analytics data for the given day range. Admin-only."""
    from app.services.History.analytics_service import get_analytics, ADMIN_USERS
    user_info = get_current_user(request)
    if user_info.get("user", "").lower() not in ADMIN_USERS:
        return JSONResponse(status_code=403, content={"status": "error", "message": "Access denied."})
    data = await get_analytics(days=days)
    return data

@router.get("/user/stats")
async def user_stats(request: Request):
    """Return personal generation/download counts for the current user."""
    import asyncio
    from app.services.History import (
        ppt_history_service,
        diagram_history_service,
        one_pager_history_service,
    )
    user_info = get_current_user(request)
    user_id = user_info.get("user", "")
    if not user_id:
        return JSONResponse(status_code=401, content={"status": "error", "message": "Not authenticated."})

    ppt_hist, diagram_hist, one_pager_hist = await asyncio.gather(
        ppt_history_service.get_history(user_id),
        diagram_history_service.get_history(user_id),
        one_pager_history_service.get_history(user_id),
    )

    return {
        "ppt": len(ppt_hist),
        "diagram": len(diagram_hist),
        "one_pager": len(one_pager_hist),
        "total": len(ppt_hist) + len(diagram_hist) + len(one_pager_hist),
    }

@router.get("/admin/feedback")
async def admin_feedback(request: Request):
    """Return per-app feedback aggregates. Admin-only."""
    from app.services.History.analytics_service import ADMIN_USERS, APP_LABELS
    from app.services.History.feedback_service import get_all_feedback_aggregates
    user_info = get_current_user(request)
    if user_info.get("user", "").lower() not in ADMIN_USERS:
        return JSONResponse(status_code=403, content={"status": "error", "message": "Access denied."})
    aggregates = await get_all_feedback_aggregates()
    return {"aggregates": aggregates, "app_labels": APP_LABELS}

