"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


@router.post("/audit-doc-check")
async def audit_doc_check(file: UploadFile = File(...)):
    """Send an uploaded audit PDF to the Audit Brain for analysis."""
    # Validate by extension - content_type header is client-controlled
    if not (file.filename or "").lower().endswith(".pdf"):
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Invalid file type",
                "detail": "Please upload a PDF file.",
            },
        )

    contents = await file.read()
    if len(contents) > MAX_UPLOAD_SIZE:
        return JSONResponse(
            status_code=400,
            content={"status": "error", "message": "File too large", "detail": "Maximum file size is 10 MB."},
        )
    if not _validate_magic(contents, file.filename or ""):
        return JSONResponse(
            status_code=400,
            content={"status": "error", "message": "Invalid file", "detail": "File content is not a valid PDF."},
        )
    await file.seek(0)

    result = await check_audit_document(file)

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Connection to Brain failed."),
            },
        )

    return {
        "status": "success", 
        "analysis": result.get("result"),
        "chatHistoryId": result.get("chatHistoryId")
    }

@router.post("/audit-chat")
async def audit_chat(
    chatHistoryId: str = Form(..., max_length=200),
    message: str = Form(..., max_length=5000),
    file: Optional[UploadFile] = File(None)
):
    """Continue audit conversation with optional file attachment."""
    if file and file.filename:
        if not (file.filename or "").lower().endswith((".pdf", ".png", ".jpg", ".jpeg")):
            return JSONResponse(
                status_code=400,
                content={"status": "error", "message": "Invalid file type", "detail": "Only PDF/PNG/JPG attachments are accepted."},
            )
        contents = await file.read()
        if len(contents) > MAX_UPLOAD_SIZE:
            return JSONResponse(
                status_code=400,
                content={"status": "error", "message": "File too large", "detail": "Maximum file size is 10 MB."},
            )
        if not _validate_magic(contents, file.filename or ""):
            return JSONResponse(
                status_code=400,
                content={"status": "error", "message": "Invalid file", "detail": "File content does not match its declared type."},
            )
        await file.seek(0)

    response = await continue_audit_chat(chatHistoryId, message, file)

    if response.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": response.get("message", "API Not Active"),
                "detail": response.get("detail", "Brain authentication failed."),
            },
        )

    return {
        "status": "success",
        "response": response.get("result"),
        "chatHistoryId": chatHistoryId
    }

