"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


class BPMNSessionRequest(BaseModel):
    processName: str = Field(default="", max_length=200)
    poolName: str = Field(default="", max_length=200)
    participants: str = Field(default="", max_length=500)
    subLanes: str = Field(default="", max_length=500)
    startTriggers: str = Field(default="", max_length=2000)
    processActivities: str = Field(default="", max_length=5000)
    processEnding: str = Field(default="", max_length=2000)
    intermediateEvents: str = Field(default="", max_length=2000)
    reviewOverride: str = Field(default="", max_length=3000)

class BPMNChatRequest(BaseModel):
    chatHistoryId: str = Field(max_length=200)
    message: str = Field(max_length=5000)
    formData: Optional[dict] = None

    @field_validator('formData')
    @classmethod
    def validate_form_data_size(cls, v):
        if v is not None:
            try:
                size = len(json.dumps(v))
            except (TypeError, ValueError):
                raise ValueError('formData must be JSON-serializable')
            if size > 50_000:
                raise ValueError('formData exceeds maximum allowed size (50 KB)')
        return v

class BPMNGenerateRequest(BaseModel):
    chatHistoryId: Optional[str] = Field(default=None, max_length=200)
    processName: str = Field(default="", max_length=200)
    poolName: str = Field(default="", max_length=200)
    participants: str = Field(default="", max_length=500)
    subLanes: str = Field(default="", max_length=500)
    startTriggers: str = Field(default="", max_length=2000)
    processActivities: str = Field(default="", max_length=5000)
    processEnding: str = Field(default="", max_length=2000)
    intermediateEvents: str = Field(default="", max_length=2000)
    reviewOverride: str = Field(default="", max_length=3000)

@router.post("/bpmn/start-session")
async def start_bpmn_session(data: BPMNSessionRequest):
    """Start a new BPMN chat session: create chat history and get initial analysis."""
    brain_id = os.getenv("SIGNAVIO_BRAIN_ID")
    if not brain_id:
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": "SIGNAVIO_BRAIN_ID is not configured.",
            },
        )

    chat_result = await create_chat_history(brain_id)
    if chat_result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": chat_result.get("message", "Failed to start session"),
                "detail": chat_result.get("detail", "Could not create chat history."),
            },
        )

    chat_history_id = chat_result.get("chatHistoryId")
    
    response = await analyze_process(data.model_dump(), chat_history_id)

    if response.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": response.get("detail", "Brain authentication failed."),
            },
        )

    return {
        "status": "success",
        "chatHistoryId": chat_history_id,
        "analysis": response.get("result")
    }

@router.post("/bpmn/chat")
async def bpmn_chat(data: BPMNChatRequest):
    """Continue the BPMN chat conversation with follow-up messages."""
    brain_id = os.getenv("SIGNAVIO_BRAIN_ID")
    if not brain_id:
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": "SIGNAVIO_BRAIN_ID is not configured.",
            },
        )

    if not data.chatHistoryId:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Missing chat session",
                "detail": "Please start a new session first.",
            },
        )

    response = await signavio_continue_chat(data.chatHistoryId, data.message, data.formData)

    if response.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": response.get("detail", "Brain authentication failed."),
            },
        )

    return {
        "status": "success",
        "chatHistoryId": data.chatHistoryId,
        "response": response.get("result")
    }

@router.post("/bpmn/upload-analyze")
async def bpmn_upload_analyze(file: UploadFile = File(...)):
    """Analyze an uploaded BPMN diagram or process image/PDF."""
    _BPMN_EXTS = (".png", ".jpg", ".jpeg", ".pdf")
    # Validate by extension - content_type header is client-controlled
    if not (file.filename or "").lower().endswith(_BPMN_EXTS):
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Invalid file type",
                "detail": "Please upload a PNG, JPG, or PDF file.",
            },
        )

    contents = await file.read()
    if len(contents) > MAX_UPLOAD_SIZE:
        return JSONResponse(
            status_code=400,
            content={"status": "error", "message": "File too large", "detail": "Maximum file size is 10 MB."},
        )
    if not _validate_magic(contents, file.filename or ""):
        return JSONResponse(
            status_code=400,
            content={"status": "error", "message": "Invalid file", "detail": "File content does not match its declared type."},
        )
    await file.seek(0)

    result = await analyze_uploaded_bpmn(file)

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Connection to Brain failed."),
            },
        )

    return {
        "status": "success",
        "analysis": result.get("result"),
        "chatHistoryId": result.get("chatHistoryId"),
        "document_valid": result.get("document_valid", True),
    }

@router.post("/generate-bpmn")
async def generate_bpmn(data: BPMNGenerateRequest):
    """Generate BPMN XML, optionally using existing chat history for context."""
    brain_id = os.getenv("SIGNAVIO_BRAIN_ID")
    if not brain_id:
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": "SIGNAVIO_BRAIN_ID is not configured.",
            },
        )
    result = await get_signavio_bpmn_xml(
        data.model_dump(), 
        chat_history_id=data.chatHistoryId
    )

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Connection to Brain failed."),
            },
        )

    process_name = data.processName or "bpmn_diagram"
    filename = f"{process_name.replace(' ', '_')}.xml"

    return {"status": "success", "xml": result.get("result"), "filename": filename}

# Legacy endpoint for backward compatibility
@router.post("/make-bpmn-analysis")
async def make_bpmn_analysis(data: dict):
    """Ask the Signavio Brain to summarize its understanding of the provided process inputs.
    
    Note: This is a legacy endpoint. Use /api/bpmn/start-session for new implementations.
    """
    brain_id = os.getenv("SIGNAVIO_BRAIN_ID")
    if not brain_id:
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": "SIGNAVIO_BRAIN_ID is not configured.",
            },
        )

    response = await analyze_process(data)

    if response.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "API Not Active",
                "detail": response.get("detail", "Brain authentication failed."),
            },
        )

    return {
        "status": "success", 
        "analysis": response.get("result"),
        "chatHistoryId": response.get("chatHistoryId")
    }

class BpmnHistorySaveRequest(BaseModel):
    content: dict

class BpmnHistoryUpdateRequest(BaseModel):
    content: dict

@router.get("/bpmn/history")
async def bpmn_history_list(request: Request):
    """Return the current user's BPMN generation history (newest first)."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        history = await bpmn_history_service.get_history(user_id)
        return {"status": "success", "history": history}
    except Exception:
        logger.exception("Failed to fetch BPMN history")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load history."})

@router.get("/bpmn/history/{gen_id}")
async def bpmn_history_get(gen_id: str, request: Request):
    """Fetch stored BPMN content for a specific generation."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await bpmn_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success", "content": content}
    except Exception:
        logger.exception("Failed to load BPMN generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load generation."})

@router.post("/bpmn/history")
async def bpmn_history_save(data: BpmnHistorySaveRequest, request: Request):
    """Save a new BPMN generation to the user's history."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        gen_id = await bpmn_history_service.save_generation(user_id, data.content)
        if gen_id is None:
            return JSONResponse(status_code=503, content={"status": "error", "message": "Storage unavailable - history not saved."})
        return {"status": "success", "genId": gen_id}
    except Exception:
        logger.exception("Failed to save BPMN generation")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save generation."})

@router.put("/bpmn/history/{gen_id}")
async def bpmn_history_update(gen_id: str, data: BpmnHistoryUpdateRequest, request: Request):
    """Update an existing BPMN generation's content after a refinement."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await bpmn_history_service.update_generation(user_id, gen_id, data.content)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found or storage unavailable."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to update BPMN generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not update generation."})

@router.delete("/bpmn/history/{gen_id}")
async def bpmn_history_delete(gen_id: str, request: Request):
    """Delete a BPMN generation from the user's history."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await bpmn_history_service.delete_generation(user_id, gen_id)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to delete BPMN generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not delete generation."})

@router.post("/bpmn/history/{gen_id}/download")
async def bpmn_history_download(gen_id: str, request: Request):
    """Stream the stored BPMN XML as a downloadable .bpmn file."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await bpmn_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})

        xml = content.get("xml", "")
        if not xml:
            return JSONResponse(status_code=404, content={"status": "error", "message": "No BPMN XML available for this generation."})

        filename = content.get("filename") or "diagram.bpmn"
        safe = "".join(c if c.isalnum() or c in "_-." else "_" for c in filename) or "diagram.bpmn"
        # Collapse path-traversal patterns and leading dots that could surface in headers/clients
        while ".." in safe:
            safe = safe.replace("..", "_")
        safe = safe.lstrip(".") or "diagram.bpmn"

        asyncio.create_task(track_download("bpmn"))
        return Response(
            content=xml.encode("utf-8"),
            media_type="application/xml",
            headers={"Content-Disposition": f'attachment; filename="{safe}"'},
        )
    except Exception:
        logger.exception("Failed to download BPMN history gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not download generation."})

