"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


class ClientLogRequest(BaseModel):
    level: str = Field(default="error", max_length=20)
    message: str = Field(default="", max_length=5000)
    metadata: Optional[str] = Field(default=None, max_length=10000)
    path: Optional[str] = Field(default=None, max_length=500)
    userAgent: Optional[str] = Field(default=None, max_length=500)
    ts: Optional[str] = Field(default=None, max_length=50)

@router.post("/client-log")
async def client_log(payload: ClientLogRequest, request: Request):
    """Collect frontend logs for production diagnostics."""
    level = (payload.level or "error").upper()
    if level.lower() not in _ALLOWED_LOG_LEVELS:
        level = "ERROR"
    message = _LOG_SANITIZE_RE.sub('', payload.message or '')[:2000]
    path = _LOG_SANITIZE_RE.sub('', payload.path or request.url.path)[:500]
    metadata = _LOG_SANITIZE_RE.sub('', payload.metadata or '')[:2000] if payload.metadata else None
    ip = request.client.host if request.client else "unknown"
    print(f"[CLIENT][{level}] {path} {message} | ip={ip}")
    if metadata:
        print(f"[CLIENT][META] {metadata}")
    return {"status": "ok"}

