"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


class ConfluenceDraftPayload(BaseModel):
    storageXml: str = Field(default="", max_length=50000)
    attachmentReferences: list[dict[str, Any]] = Field(default_factory=list)
    displayImages: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

class ConfluenceRefineRequest(BaseModel):
    chatHistoryId: str = Field(default="", max_length=200)
    instruction: str = Field(default="", max_length=5000)
    draft: ConfluenceDraftPayload

class ConfluenceVerifyRequest(BaseModel):
    confluenceUrl: str = Field(default="", max_length=500)
    pat: str = Field(default="", max_length=500)
    spaceKey: str = Field(default="", max_length=200)
    parentPageId: str = Field(default="", max_length=200)

@router.post("/confluence-builder/verify-connection")
async def confluence_builder_verify(data: ConfluenceVerifyRequest):
    """Verify PAT, space key, and parent page before proceeding."""
    logger = logging.getLogger("app.routers.api")
    if not data.pat or not data.spaceKey or not data.parentPageId:
        return JSONResponse(
            status_code=400,
            content={"status": "error", "detail": "PAT, Space Key, and Parent Page ID are required."},
        )

    logger.info("[verify-connection] Verifying space=%s parent=%s", data.spaceKey, data.parentPageId)
    try:
        result = await verify_confluence_connection(
            confluence_url=data.confluenceUrl,
            pat=data.pat,
            space_key=data.spaceKey,
            parent_page_id=data.parentPageId,
        )
    except Exception as exc:
        logger.exception("[verify-connection] Unexpected exception")
        return JSONResponse(
            status_code=500,
            content={"status": "error", "detail": "An internal error occurred"},
        )

    if result.get("error"):
        logger.warning("[verify-connection] Failed: %s", result.get("detail"))
        return JSONResponse(
            status_code=400,
            content={"status": "error", "detail": result.get("detail", "Verification failed.")},
        )

    logger.info("[verify-connection] Success: %s", result.get("displayName"))
    return {"status": "success", **result}

@router.post("/confluence-builder/generate")
async def confluence_builder_generate(
    files: List[UploadFile] = File(...),
    uploadManifest: str = Form(...),
    requestedTitle: Optional[str] = Form(None),
    instructions: Optional[str] = Form(None),
):
    """Generate a Confluence-ready draft from uploaded files."""
    if not files:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "No files provided",
                "detail": "Upload at least one file before generating the draft.",
            },
        )

    result = await generate_confluence_builder_draft(
        files,
        uploadManifest,
        requested_title=requestedTitle or "",
        instructions=instructions or "",
    )

    if result.get("error"):
        return JSONResponse(
            status_code=result.get("status_code", 500),
            content={
                "status": "error",
                "message": result.get("message", "Draft generation failed"),
                "detail": result.get("detail", "The AI service could not generate the draft."),
            },
        )

    return {
        "status": "success",
        **result,
    }

@router.post("/confluence-builder/refine")
async def confluence_builder_refine(data: ConfluenceRefineRequest):
    """Refine an existing Confluence draft."""
    result = await refine_confluence_builder_draft(
        data.draft.model_dump(),
        data.instruction,
        chat_history_id=data.chatHistoryId,
    )

    if result.get("error"):
        return JSONResponse(
            status_code=result.get("status_code", 500),
            content={
                "status": "error",
                "message": result.get("message", "Draft refinement failed"),
                "detail": result.get("detail", "The AI service could not refine the draft."),
            },
        )

    return {
        "status": "success",
        **result,
    }

@router.post("/confluence-builder/publish")
async def confluence_builder_publish(
    uploadManifest: str = Form(...),
    draft: str = Form(...),
    confluenceUrl: str = Form(""),
    pat: str = Form(""),
    spaceKey: str = Form(""),
    parentPageId: str = Form(""),
    files: Optional[List[UploadFile]] = File(None),
):
    """Publish the reviewed Confluence draft and upload selected attachments."""
    try:
        draft_payload = json.loads(draft)
    except json.JSONDecodeError:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Invalid draft payload",
                "detail": "The reviewed draft could not be parsed on the server.",
            },
        )

    if not isinstance(draft_payload, dict):
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Invalid draft payload",
                "detail": "The reviewed draft must be a JSON object.",
            },
        )

    result = await publish_confluence_builder_page(
        confluence_url=confluenceUrl,
        pat=pat,
        space_key=spaceKey,
        parent_page_id=parentPageId,
        draft=draft_payload,
        files=files or [],
        upload_manifest_json=uploadManifest,
    )

    if result.get("error"):
        return JSONResponse(
            status_code=result.get("status_code", 500),
            content={
                "status": "error",
                "message": result.get("message", "Publish failed"),
                "detail": result.get("detail", "The page could not be published to Confluence."),
            },
        )

    return result

