"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


@router.post("/diagram/analyze")
async def diagram_analyze(
    files: List[UploadFile] = File(...),
    instructions: Optional[str] = Form(None),
):
    """Upload PDF/image files → AI analyzes content and suggests diagram types."""
    MAX_TOTAL_SIZE = 10 * 1024 * 1024  # 10MB total
    _IMAGE_EXTS = (".png", ".jpg", ".jpeg")
    pdf_files = []
    image_files = []
    total_size = 0

    for f in files:
        fname_lower = f.filename.lower()
        if not fname_lower.endswith(".pdf") and not fname_lower.endswith(_IMAGE_EXTS):
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "Invalid file type",
                    "detail": f"'{f.filename}' is not supported. Only .pdf, .png, .jpg, .jpeg files are accepted.",
                },
            )
        content = await f.read()
        total_size += len(content)

        if total_size > MAX_TOTAL_SIZE:
            return JSONResponse(
                status_code=413,
                content={
                    "status": "error",
                    "message": "Total upload size too large",
                    "detail": f"Combined file size exceeds the 10 MB limit. Current total: {total_size / (1024*1024):.1f} MB.",
                },
            )

        if not _validate_magic(content, f.filename or ""):
            return JSONResponse(
                status_code=400,
                content={"status": "error", "message": "Invalid file", "detail": f"'{f.filename}' content does not match its file type."},
            )

        if fname_lower.endswith(".pdf"):
            pdf_files.append((f.filename, content))
        else:
            await f.seek(0)
            image_files.append(f)

    result = await diagram_analyze_pdf(pdf_files, instructions or "", image_files=image_files or None)

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Connection to Brain failed."),
            },
        )

    return {
        "status": "success",
        "analysis": result.get("analysis"),
        "chatHistoryId": result.get("chatHistoryId"),
        "extractedText": result.get("extractedText"),
    }

class DiagramGenerateRequest(BaseModel):
    chatHistoryId: str = Field(max_length=200)
    analysis: dict
    extractedText: str = Field(max_length=50000)
    selectedIndices: Optional[List[int]] = None

@router.post("/diagram/generate")
async def diagram_generate(data: DiagramGenerateRequest):
    """Generate draw.io XML diagrams from analysed content."""
    result = await generate_diagrams(
        data.chatHistoryId,
        data.analysis,
        data.extractedText,
        data.selectedIndices,
    )

    if result.get("error"):
        asyncio.create_task(track_generation_failed("diagram"))
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Brain request failed."),
            },
        )

    return {
        "status": "success",
        "diagrams": result.get("diagrams"),
        "chatHistoryId": result.get("chatHistoryId"),
    }

class DiagramRefineRequest(BaseModel):
    chatHistoryId: str = Field(max_length=200)
    message: str = Field(max_length=5000)
    currentXml: str = Field(default="", max_length=50000)
    diagramName: str = Field(default="", max_length=200)

@router.post("/diagram/refine")
async def diagram_refine(data: DiagramRefineRequest):
    """Refine a specific diagram based on user feedback."""
    result = await refine_diagram(
        data.chatHistoryId,
        data.message,
        data.currentXml,
        data.diagramName,
    )

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Brain request failed."),
            },
        )

    return {
        "status": "success",
        "xml": result.get("xml"),
        "chatHistoryId": result.get("chatHistoryId"),
    }

class DiagramDownloadRequest(BaseModel):
    diagrams: list

@router.post("/diagram/copy-image")
async def diagram_copy_image(
    files: List[UploadFile] = File(...),
):
    """Reproduce image-based diagram(s) as exact draw.io XML - images only, no PDFs."""
    _IMAGE_EXTS = (".png", ".jpg", ".jpeg")
    MAX_TOTAL_SIZE = 10 * 1024 * 1024
    MAX_IMAGES = 3

    image_files = []
    total_size = 0

    for f in files:
        fname_lower = f.filename.lower()

        if fname_lower.endswith(".pdf"):
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "PDFs not supported in Copy as Diagram mode",
                    "detail": "This mode only works with image files (.png, .jpg, .jpeg). Please remove all PDF files and try again.",
                },
            )

        if not any(fname_lower.endswith(ext) for ext in _IMAGE_EXTS):
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "Unsupported file type",
                    "detail": f"'{f.filename}' is not a supported image. Only .png, .jpg, .jpeg files are accepted.",
                },
            )

        content = await f.read()
        total_size += len(content)

        if total_size > MAX_TOTAL_SIZE:
            return JSONResponse(
                status_code=413,
                content={
                    "status": "error",
                    "message": "Total upload size too large",
                    "detail": f"Combined file size exceeds the 10 MB limit.",
                },
            )

        if not _validate_magic(content, f.filename or ""):
            return JSONResponse(
                status_code=400,
                content={"status": "error", "message": "Invalid file", "detail": f"'{f.filename}' content does not match its file type."},
            )

        await f.seek(0)
        image_files.append(f)

        if len(image_files) > 1:
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "Only 1 image allowed",
                    "detail": "Copy as Diagram supports exactly 1 image at a time. Please upload a single image file.",
                },
            )

    if not image_files:
        return JSONResponse(
            status_code=400,
            content={"status": "error", "message": "No images provided", "detail": "Please upload at least one image file."},
        )

    result = await copy_image_as_diagram(image_files)

    if result.get("error"):
        status_code = 500
        if result.get("message") in {"Request Timed Out", "Gateway Timeout"}:
            status_code = 504
        elif result.get("message") in {"AI Service Unavailable"}:
            status_code = 503
        elif result.get("message") in {"Upstream Service Error"}:
            status_code = 502
        return JSONResponse(
            status_code=status_code,
            content={
                "status": "error",
                "message": result.get("message", "Copy failed"),
                "detail": result.get("detail", ""),
            },
        )

    if result.get("not_a_diagram"):
        return {
            "status": "not_a_diagram",
            "content_type": result.get("content_type"),
            "suggestion": result.get("suggestion"),
            "chatHistoryId": result.get("chatHistoryId"),
        }

    return {
        "status": "success",
        "diagrams": result.get("diagrams"),
        "chatHistoryId": result.get("chatHistoryId"),
    }

@router.post("/diagram/download")
async def diagram_download(data: DiagramDownloadRequest):
    """Build and download a .drawio file from generated diagrams."""
    from fastapi.responses import Response

    if not data.diagrams:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "No diagrams provided",
                "detail": "Please generate diagrams first.",
            },
        )

    drawio_content = build_drawio_download(data.diagrams)
    asyncio.create_task(track_download("diagram"))

    return Response(
        content=drawio_content,
        media_type="application/xml",
        headers={"Content-Disposition": 'attachment; filename="diagrams.drawio"'},
    )

class DiagramHistorySaveRequest(BaseModel):
    content: dict
    chatHistoryId: str = Field(max_length=200)

class DiagramHistoryUpdateRequest(BaseModel):
    content: dict

@router.get("/diagram/history")
async def diagram_history_list(request: Request):
    """Return the current user's diagram generation history (newest first)."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        history = await diagram_history_service.get_history(user_id)
        return {"status": "success", "history": history}
    except Exception:
        logger.exception("Failed to fetch diagram history")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load history."})

@router.get("/diagram/history/{gen_id}")
async def diagram_history_get(gen_id: str, request: Request):
    """Fetch stored diagram content for a specific generation (used by Load action)."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await diagram_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success", "content": content}
    except Exception:
        logger.exception("Failed to load diagram generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load generation."})

@router.post("/diagram/history")
async def diagram_history_save(data: DiagramHistorySaveRequest, request: Request):
    """Save a new generation to the user's history after their first download."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        gen_id = await diagram_history_service.save_generation(
            user_id, data.content, data.chatHistoryId
        )
        if gen_id is None:
            return JSONResponse(status_code=503, content={"status": "error", "message": "Storage unavailable - history not saved."})
        return {"status": "success", "genId": gen_id}
    except Exception:
        logger.exception("Failed to save diagram generation")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save generation."})

@router.put("/diagram/history/{gen_id}")
async def diagram_history_update(gen_id: str, data: DiagramHistoryUpdateRequest, request: Request):
    """Update an existing generation's content after a refinement + re-download."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await diagram_history_service.update_generation(user_id, gen_id, data.content)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found or storage unavailable."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to update diagram generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not update generation."})

@router.delete("/diagram/history/{gen_id}")
async def diagram_history_delete(gen_id: str, request: Request):
    """Delete a generation from the user's history."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await diagram_history_service.delete_generation(user_id, gen_id)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to delete diagram generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not delete generation."})

class DiagramHistoryDownloadRequest(BaseModel):
    username: str = Field(default="Unknown User", max_length=200)

@router.post("/diagram/history/{gen_id}/download")
async def diagram_history_download(gen_id: str, data: DiagramHistoryDownloadRequest, request: Request):
    """Re-generate and stream a .drawio from a stored generation."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await diagram_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})

        drawio_content = build_drawio_download(content.get("diagrams", []))
        title = content.get("title", "Diagrams").replace(" ", "_")
        safe = "".join(c if c.isalnum() or c in "_-" else "" for c in title) or "Diagrams"
        asyncio.create_task(track_download("diagram"))

        return Response(
            content=drawio_content,
            media_type="application/xml",
            headers={"Content-Disposition": f'attachment; filename="{safe}.drawio"'},
        )
    except Exception:
        logger.exception("Failed to download diagram history gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not download generation."})

