"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


@router.get("/favorites")
async def favorites_get(request: Request):
    """Return the authenticated user's list of starred app keys."""
    user_id = get_current_user(request).get("user", "anonymous")
    keys = await favorites_service.get_favorites(user_id)
    return {"status": "success", "favorites": keys}

@router.post("/favorites/{app_key}")
async def favorites_add(app_key: str, request: Request):
    """Add an app key to the user's favourites."""
    if app_key not in ALLOWED_APP_KEYS:
        return JSONResponse(status_code=400, content={"status": "error", "message": "Invalid app key."})
    user_id = get_current_user(request).get("user", "anonymous")
    try:
        ok = await favorites_service.add_favorite(user_id, app_key)
        if not ok:
            return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save favourite."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to add favourite app_key=%r", app_key)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save favourite."})

@router.delete("/favorites/{app_key}")
async def favorites_remove(app_key: str, request: Request):
    """Remove an app key from the user's favourites."""
    if app_key not in ALLOWED_APP_KEYS:
        return JSONResponse(status_code=400, content={"status": "error", "message": "Invalid app key."})
    user_id = get_current_user(request).get("user", "anonymous")
    try:
        ok = await favorites_service.remove_favorite(user_id, app_key)
        if not ok:
            return JSONResponse(status_code=500, content={"status": "error", "message": "Could not remove favourite."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to remove favourite app_key=%r", app_key)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not remove favourite."})

