"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


class FeedbackRequest(BaseModel):
    gen_id: Optional[str] = Field(default=None, max_length=200)
    rating: int = Field(ge=1, le=4)

@router.post("/feedback/{app_key}")
async def submit_feedback(app_key: str, payload: FeedbackRequest, request: Request):
    """Accept a post-generation quality rating from any authenticated user."""
    from app.services.History.analytics_service import APP_LABELS
    from app.services.History.feedback_service import save_feedback
    if app_key not in APP_LABELS:
        return JSONResponse(status_code=400, content={"status": "error", "message": "Unknown app key."})
    gen_id = None
    if payload.gen_id:
        if not _GEN_ID_RE.match(payload.gen_id):
            return JSONResponse(status_code=400, content={"status": "error", "message": "Invalid gen_id format."})
        gen_id = payload.gen_id
    ok = await save_feedback(app_key, gen_id, payload.rating)
    if not ok:
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save feedback."})
    return {"status": "success"}

