"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


@router.post("/one-pager/extract")
async def one_pager_extract(
    files: List[UploadFile] = File(default=[]),
    topic: str = Form(default="", max_length=500),
    keyPoints: str = Form(default="", max_length=5000),
    audience: str = Form(default="", max_length=500),
    purpose: str = Form(default="", max_length=1000),
    templateStyle: str = Form(default="executive_summary", max_length=50),
    orientation: str = Form(default="portrait", max_length=20),
):
    """Extract content from uploaded docs and/or user context to build a one-pager."""
    _ALLOWED_EXTS = (".pdf", ".png", ".jpg", ".jpeg")
    MAX_TOTAL_SIZE = MAX_UPLOAD_SIZE

    pdf_bytes_list = []
    image_files = []
    total_size = 0

    for f in files:
        fname_lower = (f.filename or "").lower()
        if not any(fname_lower.endswith(ext) for ext in _ALLOWED_EXTS):
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "Unsupported file type",
                    "detail": f"'{f.filename}' is not supported. Only PDF and image files (.pdf, .png, .jpg, .jpeg) are accepted.",
                },
            )

        content = await f.read()
        total_size += len(content)

        if total_size > MAX_TOTAL_SIZE:
            return JSONResponse(
                status_code=413,
                content={
                    "status": "error",
                    "message": "Total upload size too large",
                    "detail": "Combined file size exceeds the 10 MB limit.",
                },
            )

        if not _validate_magic(content, f.filename or ""):
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "Invalid file",
                    "detail": f"'{f.filename}' content does not match its file type.",
                },
            )

        if fname_lower.endswith(".pdf"):
            pdf_bytes_list.append((f.filename, content))
        else:
            await f.seek(0)
            image_files.append(f)

    has_context = bool(topic or keyPoints or audience or purpose)
    if not pdf_bytes_list and not image_files and not has_context:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "No content provided",
                "detail": "Upload at least one file or fill in topic details.",
            },
        )

    safe_orientation = orientation if orientation in ("portrait", "landscape") else "portrait"
    _ALLOWED_STYLES = {
        "cheatsheet", "flyer", "executive_summary", "infographic"
    }
    safe_style = templateStyle if templateStyle in _ALLOWED_STYLES else "executive_summary"

    result = await extract_one_pager_content(
        pdf_bytes_list=pdf_bytes_list,
        topic=topic,
        key_points=keyPoints,
        audience=audience,
        purpose=purpose,
        template_style=safe_style,
        orientation=safe_orientation,
        image_files=image_files or None,
    )

    if result.get("error"):
        asyncio.create_task(track_generation_failed("one-pager"))
        status_code = 500
        msg = result.get("message", "")
        if msg in {"Request Timed Out", "Gateway Timeout"}:
            status_code = 504
        elif msg in {"AI Service Unavailable"}:
            status_code = 503
        elif msg in {"Upstream Service Error"}:
            status_code = 502
        elif msg == "No Content":
            status_code = 400
        return JSONResponse(
            status_code=status_code,
            content={
                "status": "error",
                "message": result.get("message", "Extraction failed"),
                "detail": result.get("detail", ""),
            },
        )

    return {
        "status": "success",
        "html": result.get("html"),
        "chatHistoryId": result.get("chatHistoryId"),
    }

class OnePagerRefineRequest(BaseModel):
    chatHistoryId: str = Field(max_length=200)
    message: str = Field(max_length=5000)
    currentHtml: str = Field(default="", max_length=200000)
    templateStyle: str = Field(default="executive_summary", max_length=50)
    orientation: str = Field(default="portrait", max_length=20)

@router.post("/one-pager/refine")
async def one_pager_refine(data: OnePagerRefineRequest):
    """Continue conversation to refine the one-pager HTML document."""
    safe_orientation = data.orientation if data.orientation in ("portrait", "landscape") else "portrait"
    result = await refine_one_pager_content(
        data.chatHistoryId,
        data.message,
        current_html=data.currentHtml,
        template_style=data.templateStyle,
        orientation=safe_orientation,
    )

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Brain request failed."),
            },
        )

    return {
        "status": "success",
        "html": result.get("html"),
        "chatHistoryId": result.get("chatHistoryId"),
    }

class OnePagerHistorySaveRequest(BaseModel):
    title: str = Field(default="Untitled", max_length=300)
    html: str = Field(max_length=500000)
    templateStyle: str = Field(default="executive_summary", max_length=50)
    orientation: str = Field(default="portrait", max_length=20)
    chatHistoryId: str = Field(default="", max_length=200)

class OnePagerHistoryUpdateRequest(BaseModel):
    html: str = Field(max_length=500000)
    chatHistoryId: str = Field(default="", max_length=200)
    title: Optional[str] = Field(default=None, max_length=300)

@router.get("/one-pager/history")
async def one_pager_history_list(request: Request):
    """Return the current user's one-pager generation history (newest first)."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        history = await one_pager_history_service.get_history(user_id)
        return {"status": "success", "history": history}
    except Exception:
        logger.exception("Failed to fetch one-pager history")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load history."})

@router.get("/one-pager/history/{gen_id}")
async def one_pager_history_get(gen_id: str, request: Request):
    """Fetch stored one-pager content for a specific generation."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await one_pager_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success", "content": content}
    except Exception:
        logger.exception("Failed to load one-pager generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load generation."})

@router.post("/one-pager/history")
async def one_pager_history_save(data: OnePagerHistorySaveRequest, request: Request):
    """Save a new one-pager generation to the user's history."""
    safe_orientation = data.orientation if data.orientation in ("portrait", "landscape") else "portrait"
    _ALLOWED_STYLES = {
        "executive_summary", "project_brief", "status_update",
        "technical_overview", "business_case", "cheatsheet", "flyer", "infographic",
    }
    safe_style = data.templateStyle if data.templateStyle in _ALLOWED_STYLES else "executive_summary"
    user_id = get_current_user(request).get("user", "Guest")
    try:
        gen_id = await one_pager_history_service.save_generation(
            user_id=user_id,
            title=data.title,
            html=data.html,
            template_style=safe_style,
            orientation=safe_orientation,
            chat_history_id=data.chatHistoryId,
        )
        if gen_id is None:
            return JSONResponse(status_code=503, content={"status": "error", "message": "Storage unavailable - history not saved."})
        return {"status": "success", "genId": gen_id}
    except Exception:
        logger.exception("Failed to save one-pager generation")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save generation."})

@router.put("/one-pager/history/{gen_id}")
async def one_pager_history_update(gen_id: str, data: OnePagerHistoryUpdateRequest, request: Request):
    """Update an existing one-pager generation's HTML after a refinement."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await one_pager_history_service.update_generation(
            user_id=user_id,
            gen_id=gen_id,
            html=data.html,
            chat_history_id=data.chatHistoryId,
            title=data.title,
        )
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found or storage unavailable."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to update one-pager generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not update generation."})

@router.delete("/one-pager/history/{gen_id}")
async def one_pager_history_delete(gen_id: str, request: Request):
    """Delete a one-pager generation from the user's history."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await one_pager_history_service.delete_generation(user_id, gen_id)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to delete one-pager generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not delete generation."})

