"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


@router.post("/ppt/extract")
async def ppt_extract(
    files: List[UploadFile] = File(...),
    username: str = Form(..., max_length=200),
    instructions: Optional[str] = Form(None, max_length=5000),
    force_orange_theme: bool = Form(False),
):
    """Upload PDF/image files → AI structures content into presentation slides."""
    MAX_TOTAL_SIZE = 10 * 1024 * 1024  # 10MB total across all files
    MAX_IMAGES = 3
    _IMAGE_EXTS = (".png", ".jpg", ".jpeg")
    pdf_files = []
    image_files = []
    total_size = 0

    for f in files:
        fname_lower = f.filename.lower()
        if not fname_lower.endswith(".pdf") and not fname_lower.endswith(_IMAGE_EXTS):
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "message": "Invalid file type",
                    "detail": f"'{f.filename}' is not supported. Only .pdf, .png, .jpg, .jpeg files are accepted.",
                },
            )
        content = await f.read()
        total_size += len(content)

        if total_size > MAX_TOTAL_SIZE:
            return JSONResponse(
                status_code=413,
                content={
                    "status": "error",
                    "message": "Total upload size too large",
                    "detail": f"Combined file size exceeds the 10 MB limit. Current total: {total_size / (1024*1024):.1f} MB.",
                },
            )

        if not _validate_magic(content, f.filename or ""):
            return JSONResponse(
                status_code=400,
                content={"status": "error", "message": "Invalid file", "detail": f"'{f.filename}' content does not match its file type."},
            )

        if fname_lower.endswith(".pdf"):
            pdf_files.append((f.filename, content))
        else:
            if len(image_files) >= MAX_IMAGES:
                return JSONResponse(
                    status_code=400,
                    content={
                        "status": "error",
                        "message": "Too many images",
                        "detail": f"Maximum {MAX_IMAGES} images allowed per request.",
                    },
                )
            await f.seek(0)
            image_files.append(f)

    result = await extract_pdf_content(
        pdf_files,
        instructions or "",
        username,
        image_files=image_files or None,
        force_orange_theme=force_orange_theme,
    )

    if result.get("error"):
        asyncio.create_task(track_generation_failed("ppt"))
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Connection to Brain failed."),
            },
        )

    return {
        "status": "success",
        "content": result.get("content"),
        "chatHistoryId": result.get("chatHistoryId"),
    }

class PptRefineRequest(BaseModel):
    chatHistoryId: str = Field(max_length=200)
    message: str = Field(max_length=5000)
    currentContent: Optional[dict] = None
    forceOrangeTheme: bool = False

@router.post("/ppt/refine")
async def ppt_refine(data: PptRefineRequest):
    """Continue conversation to refine presentation content."""
    result = await refine_ppt_content(
        data.chatHistoryId,
        data.message,
        data.currentContent,
        force_orange_theme=data.forceOrangeTheme,
    )

    if result.get("error"):
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": result.get("message", "API Not Active"),
                "detail": result.get("detail", "Brain request failed."),
            },
        )

    return {
        "status": "success",
        "content": result.get("content"),
        "chatHistoryId": result.get("chatHistoryId"),
        "response": result.get("result"),
    }

class PptDownloadRequest(BaseModel):
    content: dict
    username: str = Field(default="Unknown User", max_length=200)
    forceOrangeTheme: bool = False

@router.post("/ppt/download")
async def ppt_download(data: PptDownloadRequest):
    """Generate and download the .pptx file from structured AI content."""
    from fastapi.responses import StreamingResponse

    content = data.content
    username = data.username

    if not content or "slides" not in content:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Missing content",
                "detail": "No slide content provided.",
            },
        )

    try:
        buf = generate_pptx_file(content, username, force_orange_theme=data.forceOrangeTheme)
        title = content.get("title", "Presentation").replace(" ", "_")
        safe = "".join(c if c.isalnum() or c in "_-" else "" for c in title) or "Presentation"
        filename = f"{safe}.pptx"
        asyncio.create_task(track_download("ppt"))

        return StreamingResponse(
            buf,
            media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception:
        logger.exception("PPT generation failed")
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "PowerPoint generation failed",
                "detail": "An internal error occurred while generating the presentation.",
            },
        )

class PptHistorySaveRequest(BaseModel):
    content: dict
    chatHistoryId: str = Field(max_length=200)
    forceOrangeTheme: bool = False

class PptHistoryUpdateRequest(BaseModel):
    content: dict

@router.get("/ppt/history")
async def ppt_history_list(request: Request):
    """Return the current user's PPT generation history (newest first)."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        history = await ppt_history_service.get_history(user_id)
        return {"status": "success", "history": history}
    except Exception:
        logger.exception("Failed to fetch PPT history")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load history."})

@router.get("/ppt/history/{gen_id}")
async def ppt_history_get(gen_id: str, request: Request):
    """Fetch stored slide content for a specific generation (used by Load action)."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await ppt_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success", "content": content}
    except Exception:
        logger.exception("Failed to load PPT generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not load generation."})

@router.post("/ppt/history")
async def ppt_history_save(data: PptHistorySaveRequest, request: Request):
    """Save a new generation to the user's history after their first download."""
    user_id = get_current_user(request).get("user", "Guest")
    try:
        gen_id = await ppt_history_service.save_generation(
            user_id, data.content, data.chatHistoryId, data.forceOrangeTheme
        )
        if gen_id is None:
            return JSONResponse(status_code=503, content={"status": "error", "message": "Storage unavailable - history not saved."})
        return {"status": "success", "genId": gen_id}
    except Exception:
        logger.exception("Failed to save PPT generation")
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not save generation."})

@router.put("/ppt/history/{gen_id}")
async def ppt_history_update(gen_id: str, data: PptHistoryUpdateRequest, request: Request):
    """Update an existing generation's content after a refinement + re-download."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await ppt_history_service.update_generation(user_id, gen_id, data.content)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found or storage unavailable."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to update PPT generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not update generation."})

@router.delete("/ppt/history/{gen_id}")
async def ppt_history_delete(gen_id: str, request: Request):
    """Delete a generation from the user's history."""
    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        ok = await ppt_history_service.delete_generation(user_id, gen_id)
        if not ok:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})
        return {"status": "success"}
    except Exception:
        logger.exception("Failed to delete PPT generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not delete generation."})

class PptHistoryDownloadRequest(BaseModel):
    forceOrangeTheme: bool = False
    username: str = Field(default="Unknown User", max_length=200)

@router.post("/ppt/history/{gen_id}/download")
async def ppt_history_download(gen_id: str, data: PptHistoryDownloadRequest, request: Request):
    """Re-generate and stream a .pptx from a stored generation."""
    from fastapi.responses import StreamingResponse

    try:
        _validate_gen_id(gen_id)
    except ValueError:
        return JSONResponse(status_code=422, content={"status": "error", "message": "Invalid generation ID."})

    user_id = get_current_user(request).get("user", "Guest")
    try:
        content = await ppt_history_service.get_generation_content(user_id, gen_id)
        if content is None:
            return JSONResponse(status_code=404, content={"status": "error", "message": "Generation not found."})

        buf = generate_pptx_file(content, data.username, force_orange_theme=data.forceOrangeTheme)
        title = content.get("title", "Presentation").replace(" ", "_")
        safe = "".join(c if c.isalnum() or c in "_-" else "" for c in title) or "Presentation"
        asyncio.create_task(track_download("ppt"))

        return StreamingResponse(
            buf,
            media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            headers={"Content-Disposition": f'attachment; filename="{safe}.pptx"'},
        )
    except Exception:
        logger.exception("Failed to re-download PPT generation gen_id=%r", gen_id)
        return JSONResponse(status_code=500, content={"status": "error", "message": "Could not generate presentation."})

