"""Auto-generated by scripts/split_api.py — feature-scoped API router."""
from __future__ import annotations
import asyncio
import json
import os
import re
from typing import Any, Optional, List
from fastapi import APIRouter, Query, UploadFile, File, Form, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field, field_validator

from app.services.common_service import create_chat_history
from app.services.auth_service import get_current_user
from app.services.History.analytics_service import (
    track_generation, track_generation_failed, track_download,
)
from app.services.History import (
    ppt_history_service, diagram_history_service,
    bpmn_history_service, one_pager_history_service,
    favorites_service,
)
from app.services.History.favorites_service import ALLOWED_APP_KEYS
from app.services.signavio_service import (
    get_signavio_bpmn_xml, analyze_process,
    continue_chat as signavio_continue_chat,
    analyze_uploaded_bpmn,
)
from app.services.audit_service import check_audit_document, continue_audit_chat
from app.services.bpmn_checker_service import check_bpmn_diagram
from app.services.fs_br_document_service import (
    generate_functional_spec_docx, generate_br_docx, generate_fs_variant_docx,
)
from app.services.ppt_creator_service import (
    extract_pdf_content, refine_ppt_content, generate_pptx_file,
)
from app.services.diagram_generator_service import (
    analyze_pdf_content as diagram_analyze_pdf,
    generate_diagrams, refine_diagram,
    build_drawio_download, copy_image_as_diagram,
)
from app.services.confluence_builder_service import (
    generate_confluence_builder_draft, refine_confluence_builder_draft,
    publish_confluence_builder_page, verify_confluence_connection,
)
from app.services.one_pager_creator_service import (
    extract_one_pager_content, refine_one_pager_content,
)

from ._shared import (
    logger, _LOG_SANITIZE_RE, _ALLOWED_LOG_LEVELS, MAX_UPLOAD_SIZE,
    _FILE_MAGIC, _validate_magic, _GEN_ID_RE, _validate_gen_id,
)

router = APIRouter()


class FSExportRequest(BaseModel):
    title: str = Field(default="", max_length=200)
    date: str = Field(default="", max_length=50)
    version: str = Field(default="", max_length=50)
    author: str = Field(default="", max_length=200)
    responsibilities: dict = {}
    projectGoal: str = Field(default="", max_length=10000)
    solutionDesc: str = Field(default="", max_length=10000)
    improvementPotential: str = Field(default="", max_length=10000)
    delimitation: str = Field(default="", max_length=10000)
    previousSteps: list = []
    report: str = Field(default="", max_length=200)
    transaction: str = Field(default="", max_length=200)
    sourceSystem: str = Field(default="", max_length=200)
    functionality: str = Field(default="", max_length=10000)
    userView: str = Field(default="", max_length=10000)
    languageTopics: str = Field(default="", max_length=10000)
    dataStructures: str = Field(default="", max_length=10000)
    dataMaintenance: str = Field(default="", max_length=10000)
    interfaces: str = Field(default="", max_length=10000)
    authorization: str = Field(default="", max_length=10000)
    infoSecurity: str = Field(default="", max_length=10000)
    architecture: str = Field(default="", max_length=10000)
    risks: str = Field(default="", max_length=10000)
    openIssues: str = Field(default="", max_length=10000)
    migration: str = Field(default="", max_length=10000)
    glossary: list = []
    docHistory: list = []

@router.post("/export-functional-spec")
async def export_functional_spec(data: FSExportRequest):
    """Generate a .docx Functional Specification document from form data."""
    from fastapi.responses import StreamingResponse

    try:
        buffer = generate_functional_spec_docx(data.dict())
        safe_title = "".join(c if c.isalnum() or c in "_ -" else "" for c in data.title).replace(" ", "_") or "Functional_Spec"
        filename = f"{safe_title}_Functional_Specification.docx"

        asyncio.create_task(track_generation("spec-builder"))
        asyncio.create_task(track_download("spec-builder"))
        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as e:
        logger.exception("Export functional spec failed")
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "Document generation failed",
                "detail": "An internal error occurred while generating the document.",
            },
        )

class BRExportRequest(BaseModel):
    title: str = Field(default="", max_length=200)
    project: str = Field(default="", max_length=200)
    productOwner: str = Field(default="", max_length=200)
    itProduct: str = Field(default="", max_length=200)
    targetDate: str = Field(default="", max_length=50)
    requestor: str = Field(default="", max_length=200)
    requestorCompany: str = Field(default="", max_length=200)
    createDate: str = Field(default="", max_length=50)
    createdBy: str = Field(default="", max_length=200)
    responsibles: dict = {}
    description: dict = {}
    benefits: dict = {}
    signOff: dict = {}
    decision: dict = {}
    costs: dict = {}

@router.post("/export-business-requirement")
async def export_business_requirement(data: BRExportRequest):
    """Generate a .docx Business Requirement document from form data."""
    from fastapi.responses import StreamingResponse

    try:
        buffer = generate_br_docx(data.model_dump())
        title = data.title or "Business_Requirement"
        safe_name = "".join(c if c.isalnum() or c in "_ -" else "" for c in title).replace(" ", "_") or "Business_Requirement"
        filename = f"{safe_name}_Business_Requirement.docx"

        asyncio.create_task(track_generation("spec-builder"))
        asyncio.create_task(track_download("spec-builder"))
        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as e:
        logger.exception("Export business requirement failed")
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "Business Requirement document generation failed",
                "detail": "An internal error occurred while generating the document.",
            },
        )

class FSVariantExportRequest(BaseModel):
    description: str = Field(default="", max_length=200)
    writtenBy: str = Field(default="", max_length=200)
    date: str = Field(default="", max_length=50)
    updatedBy: str = Field(default="", max_length=200)
    version: str = Field(default="", max_length=50)
    revisionHistory: list = []
    purpose: str = Field(default="", max_length=10000)
    type: str = Field(default="", max_length=200)
    latency: str = Field(default="", max_length=200)
    frequency: str = Field(default="", max_length=200)
    system: str = Field(default="", max_length=200)
    impactedSystem: str = Field(default="", max_length=200)
    processingLogic: str = Field(default="", max_length=10000)
    prerequisites: str = Field(default="", max_length=5000)
    selectionScreen: list = []
    reportCharacteristics: dict = {}
    reportDelivery: str = Field(default="", max_length=5000)
    reportLayout: str = Field(default="", max_length=5000)
    reportAttributes: str = Field(default="", max_length=5000)
    customTransitions: str = Field(default="", max_length=5000)
    printerRequirements: str = Field(default="", max_length=2000)
    exclusions: str = Field(default="", max_length=5000)
    outputFileLocation: str = Field(default="", max_length=500)
    outputFileRemarks: str = Field(default="", max_length=2000)
    exceptionHandling: str = Field(default="", max_length=5000)
    constraints: str = Field(default="", max_length=5000)
    dependencies: str = Field(default="", max_length=5000)
    scheduling: str = Field(default="", max_length=2000)
    roleAuthorization: str = Field(default="", max_length=5000)
    testScenarios: list = []
    testData: str = Field(default="", max_length=5000)
    testSystem: str = Field(default="", max_length=200)
    testClient: str = Field(default="", max_length=200)
    changeHistory: list = []

@router.post("/export-fs-variant")
async def export_fs_variant(data: FSVariantExportRequest):
    """Generate a .docx FS Template (variant) document from form data."""
    from fastapi.responses import StreamingResponse

    try:
        buffer = generate_fs_variant_docx(data.model_dump())
        safe_title = "".join(c if c.isalnum() or c in "_ -" else "" for c in data.description).replace(" ", "_") or "FS_Template"
        filename = f"{safe_title}_Functional_Specification.docx"

        asyncio.create_task(track_generation("spec-builder"))
        asyncio.create_task(track_download("spec-builder"))
        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as e:
        logger.exception("Export FS template failed")
        return JSONResponse(
            status_code=500,
            content={
                "status": "error",
                "message": "FS Template document generation failed",
                "detail": "An internal error occurred while generating the document.",
            },
        )

